/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lowercase;

public class App {

    public static void main(String[] args) {
        Lowercaser lowercaser = new Lowercaser("nÕg","ga-US");

        System.out.println(lowercaser.getLowerCase());
    }
}
