/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lowercase;

public class App {

    public static void main(String[] args) {
        System.out.println("To test it, import the project and run AppTest.java");
    }
}
